/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPlanActionIndexRouteImport } from './routes/_auth/plan-action/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthChecklistIndexRouteImport } from './routes/_auth/checklist/index'
import { Route as AuthChecklistMeasureIdIndexRouteImport } from './routes/_auth/checklist/$measureId/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPlanActionIndexRoute = AuthPlanActionIndexRouteImport.update({
  id: '/plan-action/',
  path: '/plan-action/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChecklistIndexRoute = AuthChecklistIndexRouteImport.update({
  id: '/checklist/',
  path: '/checklist/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChecklistMeasureIdIndexRoute =
  AuthChecklistMeasureIdIndexRouteImport.update({
    id: '/checklist/$measureId/',
    path: '/checklist/$measureId/',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/checklist': typeof AuthChecklistIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/plan-action': typeof AuthPlanActionIndexRoute
  '/checklist/$measureId': typeof AuthChecklistMeasureIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/checklist': typeof AuthChecklistIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/plan-action': typeof AuthPlanActionIndexRoute
  '/checklist/$measureId': typeof AuthChecklistMeasureIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/checklist/': typeof AuthChecklistIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/plan-action/': typeof AuthPlanActionIndexRoute
  '/_auth/checklist/$measureId/': typeof AuthChecklistMeasureIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/checklist'
    | '/dashboard'
    | '/plan-action'
    | '/checklist/$measureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/checklist'
    | '/dashboard'
    | '/plan-action'
    | '/checklist/$measureId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/checklist/'
    | '/_auth/dashboard/'
    | '/_auth/plan-action/'
    | '/_auth/checklist/$measureId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/plan-action/': {
      id: '/_auth/plan-action/'
      path: '/plan-action'
      fullPath: '/plan-action'
      preLoaderRoute: typeof AuthPlanActionIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/checklist/': {
      id: '/_auth/checklist/'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthChecklistIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/checklist/$measureId/': {
      id: '/_auth/checklist/$measureId/'
      path: '/checklist/$measureId'
      fullPath: '/checklist/$measureId'
      preLoaderRoute: typeof AuthChecklistMeasureIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthChecklistIndexRoute: typeof AuthChecklistIndexRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthPlanActionIndexRoute: typeof AuthPlanActionIndexRoute
  AuthChecklistMeasureIdIndexRoute: typeof AuthChecklistMeasureIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChecklistIndexRoute: AuthChecklistIndexRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthPlanActionIndexRoute: AuthPlanActionIndexRoute,
  AuthChecklistMeasureIdIndexRoute: AuthChecklistMeasureIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
